server:
  port: 8080

spring:
  datasource:
    username: sa
    password:
    driver-class-name: org.h2.Driver
    hikari:
      minimum-idle: 2
      maximum-pool-size: 3
      idle-timeout: 600000
    url: jdbc:h2:~/avantedb
  jpa:
    hibernate:
      ddl-auto: create
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
        default_batch_fetch_size: 500
        jdbc:
          batch_size: 500
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
