spring:
  profiles:
    active: local

auth:
  white-list:
    - /swagger-ui/**
    - /members/v1/sign-up
    - /members/v1/login
    - /v2/api-docs
    - /v3/api-docs
    - /configuration/**
    - /swagger*/**
    - /webjars/**
    - /h2-console/**
  cors:
    allowed-origin:
      - http://localhost:8080
