spring:
  profiles:
    active: local

auth:
  white-list:
    - /swagger-ui/**
    - /v1/health
    - /v1/auth/**
    - /v2/api-docs
    - /v3/api-docs
    - /configuration/**
    - /swagger*/**
    - /webjars/**
    - /v1/**
    - /h2-console/**
  cors:
    allowed-origin:
      - http://localhost:8080
